import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import UILibProvider from "@/providers/UILibProvider";

export const metadata: Metadata = {
  title: "Easy Events",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <UILibProvider>{children}</UILibProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
